# --- !Ups
CREATE TABLE POLLS (
  ID SERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  SLUG VARCHAR NOT NULL UNIQUE,
  DESCRIPTION VARCHAR NOT NULL);

CREATE INDEX ON POLLS(SLUG);

CREATE TABLE ALTERNATIVES (
  ID SERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  POLL_ID BIGINT NOT NULL REFERENCES POLLS(ID) ON DELETE CASCADE
);

CREATE TABLE VOTES (
  ID SERIAL NOT NULL PRIMARY KEY,
  USER VARCHAR NOT NULL,
  POLL_ID BIGINT NOT NULL REFERENCES POLLS(ID) ON DELETE CASCADE
);

CREATE TABLE NOTES (
  ID SERIAL NOT NULL PRIMARY KEY,
  VOTE_ID BIGINT NOT NULL REFERENCES VOTES(ID) ON DELETE CASCADE,
  VALUE INTEGER NOT NULL DEFAULT 50,
  ALTERNATIVE_ID BIGINT NOT NULL REFERENCES ALTERNATIVES(ID)
);

# --- !Downs
DROP TABLE ALTERNATIVES;
DROP TABLE NOTES;
DROP TABLE VOTES;
DROP TABLE POLLS;
