package javascripts

object JavaScripts {

  val chooze = """(function(){var e=function(a,c){var b=void 0,b=a.parentNode;return b=null!==b?c(b)?b:e(b,c):null},g=document.querySelectorAll("form"),f=function(a){for(var c=[],b=0,d=a.length;b<d;b++)c.push(a.item(b));return c};f(g).forEach(function(a){var c=a.querySelectorAll("input[type=submit], button:not([type=button])"),b=f(c);a.addEventListener("submit",function(){b.forEach(function(a){a.disabled=!0})},!1)});var d=document.querySelector("form.change-locale");null!==d&&d.addEventListener("change",function(){d.submit()},
!1);var h=function(a){return a.classList.contains("notification")};document.addEventListener("click",function(a){if(a.target.classList.contains("close-notification")&&(a=e(a.target,h),null!==a)){var c=a.parentNode;null!==c&&c.removeChild(a)}},!1)})();"""

  val vote = """(function(){var d=document.querySelector("form");if(null!==d){for(var f=function(b,c){var a=void 0,a=b.previousSibling;return a=null!==a?c(a)?a:f(a,c):null},g=d.querySelectorAll(".alternative > input[type=range]"),h=[],e=0,i=g.length;e<i;e++)h.push(g.item(e));var j=function(b){return"name"==b.className};d.addEventListener("change",function(b){var c=b.target;h.filter(function(a){return a==c}).forEach(function(a){var b=f(a,j);null!==b&&(b=b.style,a=100+8*parseInt(a.value,10),b.fontWeight=a)})},!1)}})();"""

  val pollForm = """function pollForm(j,k){var e=document.querySelector("form");if(null!==e){var f=document.querySelector(".alternatives");if(null!==f){var g=document.querySelector(".add-alternative");if(null!==g){var h=function(a,b){var c=void 0,c=a.parentNode;return c=null!==c?b(c)?c:h(c,b):null},l=function(a){return"alternative"==a.className},i=function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a.item(c));return b};e.addEventListener("click",function(a){if("button remove-alternative"==a.target.className&&(a=h(a.target,
l),null!==a)){var b=a.parentNode;null!==b&&b.removeChild(a);a=f.querySelectorAll("input");i(a).forEach(function(a,b){a.name="alternatives["+b+"]"})}},!1);var e=[],m=0==e.length,n=e.join(", ");g.addEventListener("click",function(){var a=f.querySelectorAll(".alternative"),a="alternatives["+i(a).length+"]",b=document.createElementNS("http://www.w3.org/1999/xhtml","input");b.setAttribute("name",a);b.setAttribute("placeholder",j);b.setAttribute("class","required");b.setAttribute("type","text");b.setAttribute("value",
"");a=document.createElementNS("http://www.w3.org/1999/xhtml","div");a.setAttribute("style","display: inline-block; width: 95%;");a.appendChild(b);var c=document.createTextNode("\u00d7"),b=document.createElementNS("http://www.w3.org/1999/xhtml","span");b.setAttribute("class","button remove-alternative");b.setAttribute("title",k);b.appendChild(c);if(m)c=document.createElementNS("http://www.w3.org/1999/xhtml","span");else{var c=document.createTextNode(n),d=document.createElementNS("http://www.w3.org/1999/xhtml",
"div");d.setAttribute("class","error");d.appendChild(c);c=d}d=document.createElementNS("http://www.w3.org/1999/xhtml","div");d.setAttribute("class","alternative");d.appendChild(a);d.appendChild(b);d.appendChild(c);f.appendChild(d);a=d.querySelector("input");null!==a&&a.focus()},!1)}}}};"""

}
