package javascripts

object JavaScripts {

  val chooze = """(function(){var g=function(a,c){var b=void 0,b=a.parentNode;return b=null!==b?c(b)?b:g(b,c):null},d=document.querySelector("form");if(null!==d){for(var h=d.querySelectorAll("input[type=submit], button:not([type=button])"),i=[],e=0,j=h.length;e<j;e++)i.push(h.item(e));d.addEventListener("submit",function(){i.forEach(function(a){a.disabled=!0})},!1)}var f=document.querySelector("form.change-locale");null!==f&&f.addEventListener("change",function(){f.submit()},!1);var k=function(a){return a.classList.contains("notification")};
document.addEventListener("click",function(a){if(a.target.classList.contains("button")&&(a=g(a.target,k),null!==a)){var c=a.parentNode;null!==c&&c.removeChild(a)}},!1)})();"""

  val vote = """(function(){var d=document.querySelector("form");if(null!==d){for(var f=function(b,c){var a=void 0,a=b.previousSibling;return a=null!==a?c(a)?a:f(a,c):null},g=d.querySelectorAll(".alternative > input[type=range]"),h=[],e=0,i=g.length;e<i;e++)h.push(g.item(e));var j=function(b){return"name"==b.className};d.addEventListener("change",function(b){var c=b.target;h.filter(function(a){return a==c}).forEach(function(a){var b=f(a,j);null!==b&&(b=b.style,a=100+8*parseInt(a.value,10),b.fontWeight=a)})},!1)}})();"""

  val pollForm = """function pollForm(k,l){var f=document.querySelector("form");if(null!==f){var e=document.querySelector(".alternatives");if(null!==e){var g=document.querySelector(".add-alternative");if(null!==g){var h=function(a,b){var c=void 0,c=a.parentNode;return c=null!==c?b(c)?c:h(c,b):null},m=function(a){return"alternative"==a.className},i=function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a.item(c));return b};f.addEventListener("click",function(a){if("button remove-alternative"==a.target.className&&(a=h(a.target,
m),null!==a)){var b=a.parentNode;null!==b&&b.removeChild(a);a=e.querySelectorAll("input");i(a).forEach(function(a,b){a.name="alternatives["+b+"]"})}},!1);var j=[],n=0==j.length;g.addEventListener("click",function(){var a=e.querySelectorAll(".alternative"),a="alternatives["+i(a).length+"]",b=document.createElementNS("http://www.w3.org/1999/xhtml","input");b.setAttribute("name",a);b.setAttribute("placeholder",k);b.setAttribute("class","required");b.setAttribute("type","text");b.setAttribute("value",
"");a=document.createElementNS("http://www.w3.org/1999/xhtml","div");a.setAttribute("style","display: inline-block; width: 95%;");a.appendChild(b);var c=document.createTextNode("\u00d7"),b=document.createElementNS("http://www.w3.org/1999/xhtml","span");b.setAttribute("class","button remove-alternative");b.setAttribute("title",l);b.appendChild(c);if(n)c=document.createElementNS("http://www.w3.org/1999/xhtml","span");else{var c=j.join(", "),c=document.createTextNode(c),d=document.createElementNS("http://www.w3.org/1999/xhtml",
"div");d.setAttribute("class","error");d.appendChild(c);c=d}d=document.createElementNS("http://www.w3.org/1999/xhtml","div");d.setAttribute("class","alternative");d.appendChild(a);d.appendChild(b);d.appendChild(c);e.appendChild(d);a=d.querySelector("input");null!==a&&a.focus()},!1)}}}};"""

}
